unique_ids:
  forms:
    MSIMainForm: MT3PWYHPA6U54KPL6WALYZK57HZ4PRWE
  modules: {}
  server_modules:
    ServerMainModule: '171603754282967575544511.44099'
  assets:
    DSL_Logo.jpg: '1716037610859195189002862.16656'
    standard-page.html: BK5HWTQOBFSBXHKXIJFCKIMYKRXKJFG7
    theme.css: N5NVDGVVHNFZZWL4UCDAEY5YILDS4BI2
  scripts: {}
